[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arviz>=0.20.0",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "pymc>=5.19.1",
]
